const tr = {
  auth: {
    metaTitle: "Giriş Yap veya Hesap Oluştur — MemoryWedding",
    metaDesc:
      "MemoryWedding hesabınıza giriş yapın; davetiyelerinizi kaydedin, RSVP yanıtlarını takip edin ve anılarınızı yönetin.",
    eyebrow: "Hesabınız",
    signInTitle: "Tekrar hoş geldiniz",
    signInDesc: "Davetiyelerinize ve RSVP yanıtlarınıza devam edin.",
    signUpTitle: "Hesabınızı oluşturun",
    signUpDesc: "Davetiyelerinizi kaydetmek ve yayınlamak için ücretsiz hesap.",
    name: "Ad Soyad",
    namePh: "Elif Yılmaz",
    email: "E-posta",
    password: "Şifre",
    passwordHint: "En az 6 karakter.",
    signIn: "Giriş yap",
    signUp: "Hesap oluştur",
    google: "Google ile devam et",
    or: "veya",
    toSignUp: "Hesabınız yok mu? Oluşturun",
    toSignIn: "Zaten hesabınız var mı? Giriş yapın",
    loading: "Lütfen bekleyin...",
    checkEmail: "E-postanıza doğrulama bağlantısı gönderdik.",
    genericError: "Bir şeyler ters gitti. Lütfen tekrar deneyin.",
  },
  dash: {
    metaTitle: "Yönetim Paneli — Davetiyeler ve RSVP | MemoryWedding",
    metaDesc:
      "Davetiyelerinizi yönetin, yayın durumunu değiştirin ve misafirlerinizin RSVP yanıtlarını tek ekranda görün.",
    eyebrow: "Yönetim paneli",
    title: "Davetiyeleriniz",
    subtitle: "Yayınlayın, düzenleyin ve misafir yanıtlarını takip edin.",
    create: "Yeni davetiye",
    empty: "Henüz davetiyeniz yok.",
    emptyCta: "İlk davetiyenizi oluşturun",
    published: "Yayında",
    draft: "Taslak",
    view: "Görüntüle",
    unpublish: "Yayından kaldır",
    publish: "Yayınla",
    delete: "Sil",
    deleteConfirm: "Bu davetiye ve tüm RSVP yanıtları silinsin mi?",
    rsvpTitle: "RSVP yanıtları",
    rsvpEmpty: "Henüz yanıt yok.",
    guests: "misafir",
    yes: "Geliyor",
    no: "Gelemiyor",
    maybe: "Belki",
    total: "Toplam kişi",
    signOut: "Çıkış yap",
    loading: "Yükleniyor...",
  },
  invite: {
    notFoundTitle: "Davetiye bulunamadı",
    notFoundDesc: "Bu bağlantı geçersiz olabilir veya davetiye henüz yayında değil.",
    home: "Ana sayfaya dön",
    rsvpTitle: "Katılım bilgisi",
    rsvpDesc: "Lütfen katılım durumunuzu bize bildirin.",
    name: "Adınız Soyadınız",
    email: "E-posta (opsiyonel)",
    phone: "Telefon (opsiyonel)",
    status: "Katılım durumu",
    party: "Kaç kişi geleceksiniz?",
    note: "Notunuz (opsiyonel)",
    notePh: "Diyet tercihi, ulaşım notu...",
    submit: "Yanıtı gönder",
    sending: "Gönderiliyor...",
    thanksTitle: "Teşekkürler!",
    thanksDesc: "Yanıtınız çiftle paylaşıldı.",
    error: "Yanıt gönderilemedi. Lütfen tekrar deneyin.",
    yes: "Geliyorum",
    no: "Gelemiyorum",
    maybe: "Belki",
  },
};

export type AppContent = typeof tr;

const en: AppContent = {
  auth: {
    metaTitle: "Sign In or Create an Account — MemoryWedding",
    metaDesc:
      "Sign in to MemoryWedding to save your invitations, track RSVPs and manage your memories.",
    eyebrow: "Your account",
    signInTitle: "Welcome back",
    signInDesc: "Pick up where you left off with your invitations and RSVPs.",
    signUpTitle: "Create your account",
    signUpDesc: "A free account to save and publish your invitations.",
    name: "Full name",
    namePh: "Elif Yilmaz",
    email: "Email",
    password: "Password",
    passwordHint: "At least 6 characters.",
    signIn: "Sign in",
    signUp: "Create account",
    google: "Continue with Google",
    or: "or",
    toSignUp: "No account yet? Create one",
    toSignIn: "Already have an account? Sign in",
    loading: "Please wait...",
    checkEmail: "We sent a confirmation link to your inbox.",
    genericError: "Something went wrong. Please try again.",
  },
  dash: {
    metaTitle: "Dashboard — Invitations and RSVPs | MemoryWedding",
    metaDesc:
      "Manage your invitations, toggle publishing and see every guest RSVP in one place.",
    eyebrow: "Dashboard",
    title: "Your invitations",
    subtitle: "Publish, edit and follow your guests' replies.",
    create: "New invitation",
    empty: "You don't have any invitations yet.",
    emptyCta: "Create your first invitation",
    published: "Live",
    draft: "Draft",
    view: "View",
    unpublish: "Unpublish",
    publish: "Publish",
    delete: "Delete",
    deleteConfirm: "Delete this invitation and all of its RSVPs?",
    rsvpTitle: "RSVP replies",
    rsvpEmpty: "No replies yet.",
    guests: "guests",
    yes: "Attending",
    no: "Can't make it",
    maybe: "Maybe",
    total: "Total guests",
    signOut: "Sign out",
    loading: "Loading...",
  },
  invite: {
    notFoundTitle: "Invitation not found",
    notFoundDesc: "This link may be invalid or the invitation is not published yet.",
    home: "Back to home",
    rsvpTitle: "RSVP",
    rsvpDesc: "Please let us know whether you can join us.",
    name: "Your full name",
    email: "Email (optional)",
    phone: "Phone (optional)",
    status: "Attendance",
    party: "How many of you are coming?",
    note: "Your note (optional)",
    notePh: "Dietary preference, travel note...",
    submit: "Send reply",
    sending: "Sending...",
    thanksTitle: "Thank you!",
    thanksDesc: "Your reply has been shared with the couple.",
    error: "Could not send your reply. Please try again.",
    yes: "I'll be there",
    no: "Can't make it",
    maybe: "Maybe",
  },
};

export const appContent = { tr, en } as const;
