const tr = {
  autosave: "Otomatik kayıt açık",
  meta: {
    title: "Davetiye Oluştur — MemoryWedding",
    description:
      "Temanızı seçin, metinlerinizi yazın, tarih ve konumu girin, tasarımı canlı önizleyin ve davetiyenizi dakikalar içinde yayınlayın.",
  },
  back: "Ana sayfa",
  eyebrow: "Davetiye Stüdyosu",
  title: "Davetiyenizi oluşturun",
  subtitle: "Altı kısa adım. Her değişiklik sağdaki önizlemeye anında yansır.",
  sample: "Örnek içerikle doldur",
  clear: "Temizle",
  next: "Devam et",
  prev: "Geri",
  livePreview: "Canlı önizleme",
  previewHint: "Önizleme misafirlerinizin göreceği sayfanın birebir aynısıdır.",
  steps: [
    { id: "tema", label: "Tema", desc: "Görsel dilinizi seçin" },
    { id: "metinler", label: "Genel", desc: "Kategori, isimler ve davet" },
    { id: "detaylar", label: "Tarih & Konum", desc: "Ne zaman, nerede, harita" },
    { id: "premium", label: "İçerik", desc: "Müzik, Hikaye, Program" },
    { id: "onizleme", label: "Önizleme", desc: "Son kontrol" },
    { id: "yayin", label: "Yayınla", desc: "Bağlantı ve QR" },
  ],
  theme: {
    title: "Bir tema seçin",
    desc: "Renk, tipografi ve hareket dili birlikte tasarlandı. İstediğiniz zaman değiştirebilirsiniz.",
    selected: "Seçili",
  },
  texts: {
    title: "Genel Bilgiler",
    desc: "Davetiyenizin kalbi. Önce etkinlik türünü seçin.",
    category: "Etkinlik Türü",
    partnerOne: "Birinci isim",
    partnerTwo: "İkinci isim",
    headline: "Üst başlık",
    headlinePh: "Evleniyoruz",
    message: "Davet metni",
    messagePh: "Bu özel günümüzde sizi de aramızda görmekten mutluluk duyarız...",
    rsvpLabel: "RSVP buton metni",
    rsvpPh: "Katılıyorum",
    counter: "karakter",
    family: "Aile Bilgileri",
  },
  premium: {
    title: "Premium İçerikler",
    desc: "Müzik, çift hikayesi ve etkinlik programı ekleyin.",
    music: "YouTube Müzik Linki",
    musicPh: "Örn: https://youtube.com/watch?v=...",
    cover: "Kapak Fotoğrafı URL",
    story: "Hikayemiz (Tarih, Başlık, Açıklama)",
    program: "Etkinlik Programı (Saat, Başlık)",
  },
  details: {
    title: "Tarih ve konum",
    desc: "Geri sayım ve yol tarifi bu bilgilerden otomatik oluşturulur.",
    date: "Düğün tarihi",
    time: "Saat",
    venue: "Mekân adı",
    venuePh: "Sait Halim Paşa Yalısı",
    address: "Adres",
    addressPh: "Cadde, no, semt",
    city: "Şehir",
    cityPh: "İstanbul",
    map: "Google Maps Linki",
    mapPh: "Örn: https://maps.app.goo.gl/...",
    countdown: "gün kaldı",
    countdownToday: "Bugün!",
    countdownPast: "Tarih geçmişte",
  },
  preview: {
    title: "Tasarımı önizleyin",
    desc: "Masaüstü ve mobil görünümü kontrol edin, gerekiyorsa önceki adımlara dönün.",
    desktop: "Masaüstü",
    mobile: "Mobil",
    checklist: "Yayın kontrol listesi",
    ready: "Her şey hazır görünüyor.",
    missing: "Eksik alanlar var, yine de yayınlayabilirsiniz.",
    items: {
      theme: "Tema seçildi",
      names: "Çift isimleri girildi",
      message: "Davet metni yazıldı",
      date: "Tarih belirlendi",
      venue: "Mekân bilgisi eklendi",
    },
  },
  publish: {
    title: "Yayınlayın",
    desc: "Davetiyeniz benzersiz bir bağlantıda yayınlanır. Bağlantıyı paylaşın, QR kartlarınızı bastırın.",
    slug: "Davetiye bağlantısı",
    slugHint: "Sadece küçük harf, rakam ve tire kullanılabilir.",
    cta: "Davetiyeyi Yayınla",
    publishing: "Yayınlanıyor...",
    successTitle: "Davetiyeniz yayında",
    successDesc: "Bağlantıyı paylaşabilir, QR kodunu masalarınıza koyabilirsiniz.",
    copy: "Bağlantıyı kopyala",
    copied: "Kopyalandı",
    whatsapp: "WhatsApp'ta paylaş",
    qr: "QR kodunu indir",
    edit: "Düzenlemeye dön",
    note: "Yayınlamak için ücretsiz hesabınıza giriş yapmanız yeterli. Davetiyeniz anında canlıya alınır.",
  },
  inviteCard: {
    save: "Kaydedin",
    countdown: "gün kaldı",
    program: "Program",
    location: "Konum",
    directions: "Yol tarifi",
    rsvpFallback: "Katılıyorum",
    namesFallback: "İsimleriniz",
    messageFallback: "Davet metniniz burada görünecek.",
    dateFallback: "Tarih seçilmedi",
    venueFallback: "Mekân eklenmedi",
  },
};

export type BuilderContent = typeof tr;

const en: BuilderContent = {
  autosave: "Autosave enabled",
  meta: {
    title: "Create your invitation — MemoryWedding",
    description:
      "Pick a theme, write your words, set the date and venue, preview the design live and publish your invitation in minutes.",
  },
  back: "Home",
  eyebrow: "Invitation Studio",
  title: "Create your invitation",
  subtitle: "Six short steps. Every change appears instantly in the preview.",
  sample: "Fill with sample content",
  clear: "Clear",
  next: "Continue",
  prev: "Back",
  livePreview: "Live preview",
  previewHint: "The preview is exactly what your guests will see.",
  steps: [
    { id: "theme", label: "Theme", desc: "Choose your visual language" },
    { id: "texts", label: "General", desc: "Category, names and wording" },
    { id: "details", label: "Date & venue", desc: "When, where, map" },
    { id: "premium", label: "Content", desc: "Music, Story, Timeline" },
    { id: "preview", label: "Preview", desc: "Final check" },
    { id: "publish", label: "Publish", desc: "Link and QR" },
  ],
  theme: {
    title: "Choose a theme",
    desc: "Color, typography and motion designed together. You can change it any time.",
    selected: "Selected",
  },
  texts: {
    title: "General Info",
    desc: "The heart of your invitation. Select the event type first.",
    category: "Event Type",
    partnerOne: "First name",
    partnerTwo: "Second name",
    headline: "Overline",
    headlinePh: "We're getting married",
    message: "Invitation message",
    messagePh: "We would be delighted to have you with us on our special day...",
    rsvpLabel: "RSVP button label",
    rsvpPh: "I'll be there",
    counter: "characters",
    family: "Family Info",
  },
  premium: {
    title: "Premium Content",
    desc: "Add music, your story, and event timeline.",
    music: "YouTube Music Link",
    musicPh: "e.g. https://youtube.com/watch?v=...",
    cover: "Cover Photo URL",
    story: "Our Story (Date, Title, Desc)",
    program: "Event Program (Time, Title)",
  },
  details: {
    title: "Date and venue",
    desc: "The countdown and directions are generated from these details.",
    date: "Wedding date",
    time: "Time",
    venue: "Venue name",
    venuePh: "Sait Halim Pasha Mansion",
    address: "Address",
    addressPh: "Street, number, district",
    city: "City",
    cityPh: "Istanbul",
    map: "Google Maps Link",
    mapPh: "e.g. https://maps.app.goo.gl/...",
    countdown: "days to go",
    countdownToday: "Today!",
    countdownPast: "Date is in the past",
  },
  preview: {
    title: "Preview the design",
    desc: "Check desktop and mobile, and step back if anything needs a tweak.",
    desktop: "Desktop",
    mobile: "Mobile",
    checklist: "Publish checklist",
    ready: "Everything looks ready.",
    missing: "Some fields are missing, but you can still publish.",
    items: {
      theme: "Theme selected",
      names: "Couple names added",
      message: "Invitation message written",
      date: "Date set",
      venue: "Venue added",
    },
  },
  publish: {
    title: "Publish",
    desc: "Your invitation goes live on a unique link. Share it and print your QR cards.",
    slug: "Invitation link",
    slugHint: "Lowercase letters, numbers and hyphens only.",
    cta: "Publish invitation",
    publishing: "Publishing...",
    successTitle: "Your invitation is live",
    successDesc: "Share the link and put the QR code on your tables.",
    copy: "Copy link",
    copied: "Copied",
    whatsapp: "Share on WhatsApp",
    qr: "Download QR code",
    edit: "Back to editing",
    note: "Just sign in to your free account to publish. Your invitation goes live instantly.",
  },
  inviteCard: {
    save: "Save the date",
    countdown: "days to go",
    program: "Programme",
    location: "Location",
    directions: "Directions",
    rsvpFallback: "I'll be there",
    namesFallback: "Your names",
    messageFallback: "Your invitation message will appear here.",
    dateFallback: "No date selected",
    venueFallback: "No venue added",
  },
};

export const builderContent = { tr, en };
