const tr = {
  meta: {
    title: "Davetiye Oluştur — MemoryWedding",
    description:
      "Temanızı seçin, metinlerinizi yazın, tarih ve konumu girin, tasarımı canlı önizleyin ve davetiyenizi dakikalar içinde yayınlayın.",
  },
  back: "Ana sayfa",
  eyebrow: "Davetiye Stüdyosu",
  title: "Davetiyenizi oluşturun",
  subtitle: "Beş kısa adım. Her değişiklik sağdaki önizlemeye anında yansır.",
  sample: "Örnek içerikle doldur",
  clear: "Temizle",
  next: "Devam et",
  prev: "Geri",
  livePreview: "Canlı önizleme",
  previewHint: "Önizleme misafirlerinizin göreceği sayfanın birebir aynısıdır.",
  autosave: "Taslağınız bu cihazda otomatik kaydedilir.",
  steps: [
    { id: "tema", label: "Tema", desc: "Görsel dilinizi seçin" },
    { id: "metinler", label: "Metinler", desc: "İsimler ve davet yazısı" },
    { id: "detaylar", label: "Tarih & Konum", desc: "Ne zaman, nerede" },
    { id: "onizleme", label: "Önizleme", desc: "Son kontrol" },
    { id: "yayin", label: "Yayınla", desc: "Bağlantı ve QR" },
  ],
  theme: {
    title: "Bir tema seçin",
    desc: "Renk, tipografi ve hareket dili birlikte tasarlandı. İstediğiniz zaman değiştirebilirsiniz.",
    selected: "Seçili",
  },
  texts: {
    title: "Metinleriniz",
    desc: "Davetiyenizin kalbi. Kısa ve içten tutmanızı öneririz.",
    partnerOne: "Birinci isim",
    partnerTwo: "İkinci isim",
    headline: "Üst başlık",
    headlinePh: "Evleniyoruz",
    message: "Davet metni",
    messagePh: "Bu özel günümüzde sizi de aramızda görmekten mutluluk duyarız...",
    rsvpLabel: "RSVP buton metni",
    rsvpPh: "Katılıyorum",
    counter: "karakter",
  },
  details: {
    title: "Tarih ve konum",
    desc: "Geri sayım ve yol tarifi bu bilgilerden otomatik oluşturulur.",
    date: "Düğün tarihi",
    time: "Saat",
    venue: "Mekân adı",
    venuePh: "Sait Halim Paşa Yalısı",
    address: "Adres",
    addressPh: "Cadde, no, semt",
    city: "Şehir",
    cityPh: "İstanbul",
    countdown: "gün kaldı",
    countdownToday: "Bugün!",
    countdownPast: "Tarih geçmişte",
  },
  preview: {
    title: "Tasarımı önizleyin",
    desc: "Masaüstü ve mobil görünümü kontrol edin, gerekiyorsa önceki adımlara dönün.",
    desktop: "Masaüstü",
    mobile: "Mobil",
    checklist: "Yayın kontrol listesi",
    ready: "Her şey hazır görünüyor.",
    missing: "Eksik alanlar var, yine de yayınlayabilirsiniz.",
    items: {
      theme: "Tema seçildi",
      names: "Çift isimleri girildi",
      message: "Davet metni yazıldı",
      date: "Tarih belirlendi",
      venue: "Mekân bilgisi eklendi",
    },
  },
  publish: {
    title: "Yayınlayın",
    desc: "Davetiyeniz benzersiz bir bağlantıda yayınlanır. Bağlantıyı paylaşın, QR kartlarınızı bastırın.",
    slug: "Davetiye bağlantısı",
    slugHint: "Sadece küçük harf, rakam ve tire kullanılabilir.",
    cta: "Davetiyeyi Yayınla",
    publishing: "Yayınlanıyor...",
    successTitle: "Davetiyeniz yayında",
    successDesc: "Bağlantıyı paylaşabilir, QR kodunu masalarınıza koyabilirsiniz.",
    copy: "Bağlantıyı kopyala",
    copied: "Kopyalandı",
    whatsapp: "WhatsApp'ta paylaş",
    qr: "QR kodunu indir",
    edit: "Düzenlemeye dön",
    note: "Bu bir demo yayın akışıdır; canlı yayın hesabınız oluşturulduğunda aktifleşir.",
  },
  inviteCard: {
    save: "Kaydedin",
    countdown: "gün kaldı",
    program: "Program",
    location: "Konum",
    directions: "Yol tarifi",
    rsvpFallback: "Katılıyorum",
    namesFallback: "İsimleriniz",
    messageFallback: "Davet metniniz burada görünecek.",
    dateFallback: "Tarih seçilmedi",
    venueFallback: "Mekân eklenmedi",
  },
};

export type BuilderContent = typeof tr;

const en: BuilderContent = {
  meta: {
    title: "Create your invitation — MemoryWedding",
    description:
      "Pick a theme, write your words, set the date and venue, preview the design live and publish your invitation in minutes.",
  },
  back: "Home",
  eyebrow: "Invitation Studio",
  title: "Create your invitation",
  subtitle: "Five short steps. Every change appears instantly in the preview.",
  sample: "Fill with sample content",
  clear: "Clear",
  next: "Continue",
  prev: "Back",
  livePreview: "Live preview",
  previewHint: "The preview is exactly what your guests will see.",
  autosave: "Your draft is saved automatically on this device.",
  steps: [
    { id: "theme", label: "Theme", desc: "Choose your visual language" },
    { id: "texts", label: "Texts", desc: "Names and wording" },
    { id: "details", label: "Date & venue", desc: "When and where" },
    { id: "preview", label: "Preview", desc: "Final check" },
    { id: "publish", label: "Publish", desc: "Link and QR" },
  ],
  theme: {
    title: "Choose a theme",
    desc: "Color, typography and motion designed together. You can change it any time.",
    selected: "Selected",
  },
  texts: {
    title: "Your words",
    desc: "The heart of your invitation. Short and heartfelt works best.",
    partnerOne: "First name",
    partnerTwo: "Second name",
    headline: "Overline",
    headlinePh: "We're getting married",
    message: "Invitation message",
    messagePh: "We would be delighted to have you with us on our special day...",
    rsvpLabel: "RSVP button label",
    rsvpPh: "I'll be there",
    counter: "characters",
  },
  details: {
    title: "Date and venue",
    desc: "The countdown and directions are generated from these details.",
    date: "Wedding date",
    time: "Time",
    venue: "Venue name",
    venuePh: "Sait Halim Pasha Mansion",
    address: "Address",
    addressPh: "Street, number, district",
    city: "City",
    cityPh: "Istanbul",
    countdown: "days to go",
    countdownToday: "Today!",
    countdownPast: "Date is in the past",
  },
  preview: {
    title: "Preview the design",
    desc: "Check desktop and mobile, and step back if anything needs a tweak.",
    desktop: "Desktop",
    mobile: "Mobile",
    checklist: "Publish checklist",
    ready: "Everything looks ready.",
    missing: "Some fields are missing, but you can still publish.",
    items: {
      theme: "Theme selected",
      names: "Couple names added",
      message: "Invitation message written",
      date: "Date set",
      venue: "Venue added",
    },
  },
  publish: {
    title: "Publish",
    desc: "Your invitation goes live on a unique link. Share it and print your QR cards.",
    slug: "Invitation link",
    slugHint: "Lowercase letters, numbers and hyphens only.",
    cta: "Publish invitation",
    publishing: "Publishing...",
    successTitle: "Your invitation is live",
    successDesc: "Share the link and put the QR code on your tables.",
    copy: "Copy link",
    copied: "Copied",
    whatsapp: "Share on WhatsApp",
    qr: "Download QR code",
    edit: "Back to editing",
    note: "This is a demo publishing flow; it goes live once your account is created.",
  },
  inviteCard: {
    save: "Save the date",
    countdown: "days to go",
    program: "Programme",
    location: "Location",
    directions: "Directions",
    rsvpFallback: "I'll be there",
    namesFallback: "Your names",
    messageFallback: "Your invitation message will appear here.",
    dateFallback: "No date selected",
    venueFallback: "No venue added",
  },
};

export const builderContent = { tr, en };
