/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as OdemeRouteImport } from './routes/odeme'
import { Route as OlusturRouteImport } from './routes/olustur'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DavetSlugRouteImport } from './routes/davet.$slug'
import { Route as OdemeBasariliRouteImport } from './routes/odeme.basarili'
import { Route as OdemeHataRouteImport } from './routes/odeme.hata'
import { Route as PanelIdRouteImport } from './routes/panel_.$id'
import { Route as SozlesmelerGizlilikRouteImport } from './routes/sozlesmeler.gizlilik'
import { Route as SozlesmelerIptalIadeRouteImport } from './routes/sozlesmeler.iptal-iade'
import { Route as SozlesmelerMesafeliSatisRouteImport } from './routes/sozlesmeler.mesafeli-satis'
import { Route as SozlesmelerTeslimatRouteImport } from './routes/sozlesmeler.teslimat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeRoute = OdemeRouteImport.update({
  id: '/odeme',
  path: '/odeme',
  getParentRoute: () => rootRouteImport,
} as any)
const OlusturRoute = OlusturRouteImport.update({
  id: '/olustur',
  path: '/olustur',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DavetSlugRoute = DavetSlugRouteImport.update({
  id: '/davet/$slug',
  path: '/davet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeBasariliRoute = OdemeBasariliRouteImport.update({
  id: '/basarili',
  path: '/basarili',
  getParentRoute: () => OdemeRoute,
} as any)
const OdemeHataRoute = OdemeHataRouteImport.update({
  id: '/hata',
  path: '/hata',
  getParentRoute: () => OdemeRoute,
} as any)
const PanelIdRoute = PanelIdRouteImport.update({
  id: '/panel_/$id',
  path: '/panel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SozlesmelerGizlilikRoute = SozlesmelerGizlilikRouteImport.update({
  id: '/sozlesmeler/gizlilik',
  path: '/sozlesmeler/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const SozlesmelerIptalIadeRoute = SozlesmelerIptalIadeRouteImport.update({
  id: '/sozlesmeler/iptal-iade',
  path: '/sozlesmeler/iptal-iade',
  getParentRoute: () => rootRouteImport,
} as any)
const SozlesmelerMesafeliSatisRoute =
  SozlesmelerMesafeliSatisRouteImport.update({
    id: '/sozlesmeler/mesafeli-satis',
    path: '/sozlesmeler/mesafeli-satis',
    getParentRoute: () => rootRouteImport,
  } as any)
const SozlesmelerTeslimatRoute = SozlesmelerTeslimatRouteImport.update({
  id: '/sozlesmeler/teslimat',
  path: '/sozlesmeler/teslimat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/giris': typeof GirisRoute
  '/iletisim': typeof IletisimRoute
  '/odeme': typeof OdemeRouteWithChildren
  '/olustur': typeof OlusturRoute
  '/panel': typeof PanelRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/davet/$slug': typeof DavetSlugRoute
  '/odeme/basarili': typeof OdemeBasariliRoute
  '/odeme/hata': typeof OdemeHataRoute
  '/panel/$id': typeof PanelIdRoute
  '/sozlesmeler/gizlilik': typeof SozlesmelerGizlilikRoute
  '/sozlesmeler/iptal-iade': typeof SozlesmelerIptalIadeRoute
  '/sozlesmeler/mesafeli-satis': typeof SozlesmelerMesafeliSatisRoute
  '/sozlesmeler/teslimat': typeof SozlesmelerTeslimatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/giris': typeof GirisRoute
  '/iletisim': typeof IletisimRoute
  '/odeme': typeof OdemeRouteWithChildren
  '/olustur': typeof OlusturRoute
  '/panel': typeof PanelRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/davet/$slug': typeof DavetSlugRoute
  '/odeme/basarili': typeof OdemeBasariliRoute
  '/odeme/hata': typeof OdemeHataRoute
  '/panel/$id': typeof PanelIdRoute
  '/sozlesmeler/gizlilik': typeof SozlesmelerGizlilikRoute
  '/sozlesmeler/iptal-iade': typeof SozlesmelerIptalIadeRoute
  '/sozlesmeler/mesafeli-satis': typeof SozlesmelerMesafeliSatisRoute
  '/sozlesmeler/teslimat': typeof SozlesmelerTeslimatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/giris': typeof GirisRoute
  '/iletisim': typeof IletisimRoute
  '/odeme': typeof OdemeRouteWithChildren
  '/olustur': typeof OlusturRoute
  '/panel': typeof PanelRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/davet/$slug': typeof DavetSlugRoute
  '/odeme/basarili': typeof OdemeBasariliRoute
  '/odeme/hata': typeof OdemeHataRoute
  '/panel_/$id': typeof PanelIdRoute
  '/sozlesmeler/gizlilik': typeof SozlesmelerGizlilikRoute
  '/sozlesmeler/iptal-iade': typeof SozlesmelerIptalIadeRoute
  '/sozlesmeler/mesafeli-satis': typeof SozlesmelerMesafeliSatisRoute
  '/sozlesmeler/teslimat': typeof SozlesmelerTeslimatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/giris'
    | '/iletisim'
    | '/odeme'
    | '/olustur'
    | '/panel'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/davet/$slug'
    | '/odeme/basarili'
    | '/odeme/hata'
    | '/panel/$id'
    | '/sozlesmeler/gizlilik'
    | '/sozlesmeler/iptal-iade'
    | '/sozlesmeler/mesafeli-satis'
    | '/sozlesmeler/teslimat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/giris'
    | '/iletisim'
    | '/odeme'
    | '/olustur'
    | '/panel'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/davet/$slug'
    | '/odeme/basarili'
    | '/odeme/hata'
    | '/panel/$id'
    | '/sozlesmeler/gizlilik'
    | '/sozlesmeler/iptal-iade'
    | '/sozlesmeler/mesafeli-satis'
    | '/sozlesmeler/teslimat'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/giris'
    | '/iletisim'
    | '/odeme'
    | '/olustur'
    | '/panel'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/davet/$slug'
    | '/odeme/basarili'
    | '/odeme/hata'
    | '/panel_/$id'
    | '/sozlesmeler/gizlilik'
    | '/sozlesmeler/iptal-iade'
    | '/sozlesmeler/mesafeli-satis'
    | '/sozlesmeler/teslimat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GirisRoute: typeof GirisRoute
  IletisimRoute: typeof IletisimRoute
  OdemeRoute: typeof OdemeRouteWithChildren
  OlusturRoute: typeof OlusturRoute
  PanelRoute: typeof PanelRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DavetSlugRoute: typeof DavetSlugRoute
  PanelIdRoute: typeof PanelIdRoute
  SozlesmelerGizlilikRoute: typeof SozlesmelerGizlilikRoute
  SozlesmelerIptalIadeRoute: typeof SozlesmelerIptalIadeRoute
  SozlesmelerMesafeliSatisRoute: typeof SozlesmelerMesafeliSatisRoute
  SozlesmelerTeslimatRoute: typeof SozlesmelerTeslimatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme': {
      id: '/odeme'
      path: '/odeme'
      fullPath: '/odeme'
      preLoaderRoute: typeof OdemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olustur': {
      id: '/olustur'
      path: '/olustur'
      fullPath: '/olustur'
      preLoaderRoute: typeof OlusturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/davet/$slug': {
      id: '/davet/$slug'
      path: '/davet/$slug'
      fullPath: '/davet/$slug'
      preLoaderRoute: typeof DavetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme/basarili': {
      id: '/odeme/basarili'
      path: '/basarili'
      fullPath: '/odeme/basarili'
      preLoaderRoute: typeof OdemeBasariliRouteImport
      parentRoute: typeof OdemeRoute
    }
    '/odeme/hata': {
      id: '/odeme/hata'
      path: '/hata'
      fullPath: '/odeme/hata'
      preLoaderRoute: typeof OdemeHataRouteImport
      parentRoute: typeof OdemeRoute
    }
    '/panel_/$id': {
      id: '/panel_/$id'
      path: '/panel/$id'
      fullPath: '/panel/$id'
      preLoaderRoute: typeof PanelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sozlesmeler/gizlilik': {
      id: '/sozlesmeler/gizlilik'
      path: '/sozlesmeler/gizlilik'
      fullPath: '/sozlesmeler/gizlilik'
      preLoaderRoute: typeof SozlesmelerGizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sozlesmeler/iptal-iade': {
      id: '/sozlesmeler/iptal-iade'
      path: '/sozlesmeler/iptal-iade'
      fullPath: '/sozlesmeler/iptal-iade'
      preLoaderRoute: typeof SozlesmelerIptalIadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sozlesmeler/mesafeli-satis': {
      id: '/sozlesmeler/mesafeli-satis'
      path: '/sozlesmeler/mesafeli-satis'
      fullPath: '/sozlesmeler/mesafeli-satis'
      preLoaderRoute: typeof SozlesmelerMesafeliSatisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sozlesmeler/teslimat': {
      id: '/sozlesmeler/teslimat'
      path: '/sozlesmeler/teslimat'
      fullPath: '/sozlesmeler/teslimat'
      preLoaderRoute: typeof SozlesmelerTeslimatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OdemeRouteChildren {
  OdemeBasariliRoute: typeof OdemeBasariliRoute
  OdemeHataRoute: typeof OdemeHataRoute
}

const OdemeRouteChildren: OdemeRouteChildren = {
  OdemeBasariliRoute: OdemeBasariliRoute,
  OdemeHataRoute: OdemeHataRoute,
}

const OdemeRouteWithChildren = OdemeRoute._addFileChildren(OdemeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GirisRoute: GirisRoute,
  IletisimRoute: IletisimRoute,
  OdemeRoute: OdemeRouteWithChildren,
  OlusturRoute: OlusturRoute,
  PanelRoute: PanelRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DavetSlugRoute: DavetSlugRoute,
  PanelIdRoute: PanelIdRoute,
  SozlesmelerGizlilikRoute: SozlesmelerGizlilikRoute,
  SozlesmelerIptalIadeRoute: SozlesmelerIptalIadeRoute,
  SozlesmelerMesafeliSatisRoute: SozlesmelerMesafeliSatisRoute,
  SozlesmelerTeslimatRoute: SozlesmelerTeslimatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
