/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BakimRouteImport } from './routes/bakim'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as OlusturRouteImport } from './routes/olustur'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DavetSlugRouteImport } from './routes/davet.$slug'
import { Route as PanelIdRouteImport } from './routes/panel_.$id'
import { Route as ApiAdminMaintenanceBypassRouteImport } from './routes/api.admin.maintenance-bypass'
import { Route as ApiAdminSystemSettingsRouteImport } from './routes/api.admin.system-settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BakimRoute = BakimRouteImport.update({
  id: '/bakim',
  path: '/bakim',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const OlusturRoute = OlusturRouteImport.update({
  id: '/olustur',
  path: '/olustur',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DavetSlugRoute = DavetSlugRouteImport.update({
  id: '/davet/$slug',
  path: '/davet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIdRoute = PanelIdRouteImport.update({
  id: '/panel_/$id',
  path: '/panel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMaintenanceBypassRoute =
  ApiAdminMaintenanceBypassRouteImport.update({
    id: '/api/admin/maintenance-bypass',
    path: '/api/admin/maintenance-bypass',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSystemSettingsRoute = ApiAdminSystemSettingsRouteImport.update({
  id: '/api/admin/system-settings',
  path: '/api/admin/system-settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bakim': typeof BakimRoute
  '/giris': typeof GirisRoute
  '/olustur': typeof OlusturRoute
  '/panel': typeof PanelRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/davet/$slug': typeof DavetSlugRoute
  '/panel/$id': typeof PanelIdRoute
  '/api/admin/maintenance-bypass': typeof ApiAdminMaintenanceBypassRoute
  '/api/admin/system-settings': typeof ApiAdminSystemSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bakim': typeof BakimRoute
  '/giris': typeof GirisRoute
  '/olustur': typeof OlusturRoute
  '/panel': typeof PanelRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/davet/$slug': typeof DavetSlugRoute
  '/panel/$id': typeof PanelIdRoute
  '/api/admin/maintenance-bypass': typeof ApiAdminMaintenanceBypassRoute
  '/api/admin/system-settings': typeof ApiAdminSystemSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bakim': typeof BakimRoute
  '/giris': typeof GirisRoute
  '/olustur': typeof OlusturRoute
  '/panel': typeof PanelRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/davet/$slug': typeof DavetSlugRoute
  '/panel_/$id': typeof PanelIdRoute
  '/api/admin/maintenance-bypass': typeof ApiAdminMaintenanceBypassRoute
  '/api/admin/system-settings': typeof ApiAdminSystemSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bakim'
    | '/giris'
    | '/olustur'
    | '/panel'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/davet/$slug'
    | '/panel/$id'
    | '/api/admin/maintenance-bypass'
    | '/api/admin/system-settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bakim'
    | '/giris'
    | '/olustur'
    | '/panel'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/davet/$slug'
    | '/panel/$id'
    | '/api/admin/maintenance-bypass'
    | '/api/admin/system-settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bakim'
    | '/giris'
    | '/olustur'
    | '/panel'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/davet/$slug'
    | '/panel_/$id'
    | '/api/admin/maintenance-bypass'
    | '/api/admin/system-settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BakimRoute: typeof BakimRoute
  GirisRoute: typeof GirisRoute
  OlusturRoute: typeof OlusturRoute
  PanelRoute: typeof PanelRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DavetSlugRoute: typeof DavetSlugRoute
  PanelIdRoute: typeof PanelIdRoute
  ApiAdminMaintenanceBypassRoute: typeof ApiAdminMaintenanceBypassRoute
  ApiAdminSystemSettingsRoute: typeof ApiAdminSystemSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakim': {
      id: '/bakim'
      path: '/bakim'
      fullPath: '/bakim'
      preLoaderRoute: typeof BakimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olustur': {
      id: '/olustur'
      path: '/olustur'
      fullPath: '/olustur'
      preLoaderRoute: typeof OlusturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/davet/$slug': {
      id: '/davet/$slug'
      path: '/davet/$slug'
      fullPath: '/davet/$slug'
      preLoaderRoute: typeof DavetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel_/$id': {
      id: '/panel_/$id'
      path: '/panel/$id'
      fullPath: '/panel/$id'
      preLoaderRoute: typeof PanelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/maintenance-bypass': {
      id: '/api/admin/maintenance-bypass'
      path: '/api/admin/maintenance-bypass'
      fullPath: '/api/admin/maintenance-bypass'
      preLoaderRoute: typeof ApiAdminMaintenanceBypassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/system-settings': {
      id: '/api/admin/system-settings'
      path: '/api/admin/system-settings'
      fullPath: '/api/admin/system-settings'
      preLoaderRoute: typeof ApiAdminSystemSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BakimRoute: BakimRoute,
  GirisRoute: GirisRoute,
  OlusturRoute: OlusturRoute,
  PanelRoute: PanelRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DavetSlugRoute: DavetSlugRoute,
  PanelIdRoute: PanelIdRoute,
  ApiAdminMaintenanceBypassRoute: ApiAdminMaintenanceBypassRoute,
  ApiAdminSystemSettingsRoute: ApiAdminSystemSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
